figure
hmO=uimenu('label','Option');
hmOsub1=uimenu(hmO,'label','Grid on',...			%显示网格
	'callback',[...
		'grid on,',...
		'set(hmOsub1,''checked'',''on''),',...
		'set(hmOsub2,''checked'',''off''),',...
	                 ]);
hmOsub2=uimenu(hmO,'label','Grid off',...			%不显示网格
	'callback',[...
		'grid off,',...
		'set(hmOsub2,''checked'',''on''),',...
		'set(hmOsub1,''checked'',''off''),',...
		               ]); 
