hrboxoff=uicontrol(hf,'Style','radio',...
               'Position',[50 180 100 20],...
               'String','Set box off',...
               'Value',0,...
               'CallBack',[...
                   'set(hrboxon,''Value'',0);'...
                   'set(hrboxoff,''Value'',1);'...
                   'set(gca,''Box'',''off'');']);
               
hrboxon=uicontrol(hf,'Style','radio',...
                'Position',[50 210 100 20],...
                'String','Set box on',...
                'Value',1,...
                'CallBack',[...
                    'set(hrboxon,''Value'',1);'...
                   'set(hrboxoff,''Value'',0);'...
                   'set(gca,''Box'',''on'');']);   