function guihd(arg)
if nargin==0
    arg='Initialize';
end
switch arg
    case 'Initialize'
    hf=figure('Position',[200 200 600 400] ,...
           'Name','GUI_hd' ,...
           'NumberTitle','off');
    ha=axes('Position',[0.4 0.1 0.5 0.7],...
        'Box','on');
    hbSin=uicontrol(hf,...
                'Style','pushbutton',...
                'Position',[50,140,100,30],...
                'String','Plot sin(x)',...
                'CallBack',...
                [ 'x=0:0.1:4*pi;'...
                  'plot(x,sin(x));'...
                  'axis([0 4*pi -1 1]);'...
                  'xlabel(''x'');'...
                 'ylabel(''y=sin(x)'');'...
                ]);  
    hbCos=uicontrol(hf,...
                'Style','pushbutton',...
                'Position',[50,100,100,30],...
                'String','Plot cos(x)',...
                'CallBack',...
                ['x=0:0.1:4*pi;'...
                  'plot(x,cos(x));'...
                  'axis([0 4*pi -1 1]);'...
                'xlabel(''x'');'...
                 'ylabel(''y=cos(x)'');'...
                   ]);             
    hbClose=uicontrol(hf,...
                'Style','pushbutton',...
                'Position',[50,60,100,30],...
                'String','Exit',...
                'CallBack','close'); 
    case 'Plot sin(x)'
        %...
    case 'Plot cos(x)'
        %...
    case 'Exit'
        %...
    otherwise
       errordlg('输入参数错误！','错误提示');
end
