function guihd1(arg)
if nargin==0
    arg='Initialize';
end
switch arg
    case 'Initialize'
hf=figure('Position',[200 200 600 400] ,...
           'Name','GUI_hd' ,...
           'NumberTitle','off');
ha=axes('Position',[0.4 0.1 0.5 0.7],...
        'Box','on');
hbSin=uicontrol(hf,...
                'Style','pushbutton',...
                'Position',[50,140,100,30],...
                'String','Plot sin(x)',...
                'CallBack','guihd_sin');  
hbCos=uicontrol(hf,...
                'Style','pushbutton',...
                'Position',[50,100,100,30],...
                'String','Plot cos(x)',...
                'CallBack','guihd_cos');             
hbClose=uicontrol(hf,...
                'Style','pushbutton',...
                'Position',[50,60,100,30],...
                'String','Exit',...
                'CallBack','close');  
    case 'Plot sin(x)'
        %...
    case 'Plot cos(x)'
        %...
    case 'Exit'
        %...
    otherwise
       errordlg('输入参数错误！','错误提示');
end