function guihd2
    hf=figure('Position',[200 200 600 400] ,...
           'Name','GUI_hd' ,...
           'NumberTitle','off');
    ha=axes('Position',[0.4 0.1 0.5 0.7],...
        'Box','on');
    hbSin=uicontrol(hf,...
                'Style','pushbutton',...
                'Position',[50,140,100,30],...
                'String','Plot sin(x)',...
                'CallBack',@hd_sin);  
    hbCos=uicontrol(hf,...
                'Style','pushbutton',...
                'Position',[50,100,100,30],...
                'String','Plot cos(x)',...
                'CallBack',@hd_cos);             
    hbClose=uicontrol(hf,...
                'Style','pushbutton',...
                'Position',[50,60,100,30],...
                'String','Exit',...
                'CallBack','close');
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function hd_sin(cbo,eventdata)
x=0:0.1:4*pi;
plot(x,sin(x));
axis([0 4*pi -1 1]);
xlabel('x');...
ylabel('y=sin(x)');
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function hd_cos(cbo,eventdata)
x=0:0.1:4*pi;
plot(x,cos(x));
axis([0 4*pi -1 1]);
xlabel('x');
ylabel('y=cos(x)');
 
