%********************************************************
%程序：EX201.M
%功能：作出具有较为完整流程的二维图形
%********************************************************
function createfigure(x1, y1)                    %创建图形绘制函数
x1=0:0.02*pi:2*pi;                                   % 定义X1的范围及刻度
y1=[sin(x1);sin(2*x1);sin(3*x1)];                %定义Y1的范围及刻度
figure1 = figure('PaperPosition',[0.6345 6.345 20.3 15.23],'PaperSize',[20.98 29.68]);
%建立绘图区
axes1 = axes('Parent',figure1);         %设立坐标轴模式
axis(axes1,[0 6.283 -2 2]);               %建立坐标轴
title(axes1,'sin(x)/sin(2x)/sin(3x)');  %图形标注
xlabel(axes1,'x');                           %加入x坐标轴标注
ylabel(axes1,'y');                           %加入y坐标轴标注
box(axes1,'on');
hold(axes1,'all');                          %设立坐标轴叠加模式
 plot1 = plot(x1,y1);                       %显示图形
 text1 = text(...
  'Position',[1.136 -0.9532 0],...
  'String','y=sin(x)',...
  'VerticalAlignment','baseline',...
  'Parent',axes1);                             %创立文字标注
 
text2 = text(...
  'Position',[2.266 -0.8947 0],...
  'String','y=sin(2x)',...
  'VerticalAlignment','baseline',...
  'Parent',axes1);                             %创立文字标注
  
text3 = text(...
  'Position',[3.395 0.8947 0],...
  'String','y=sin(3x)',...
  'VerticalAlignment','baseline',...
  'Parent',axes1);                              %创立文字标注
