[FileName,PathName,FilterIndex]=uigetfile( ...
{   '*.m',  'M-files (*.m)'; ...
   '*.fig','Figures (*.fig)'; ...
   '*.mat','MAT-files (*.mat)'; ...
   '*.mdl','Models (*.mdl)'; ...
   '*.*',  'All Files (*.*)'}, ...
   'Ñ¡ÔñÎÄ¼þ')
